### ISSUE TITLE
Add a doc for ngspyce ?

### ISSUE THREAD

**Issue by liubenyuan** [ignamv/ngspyce#1]
Hi, thanks for sharing ngspyce.

I plan to use it for circuit simulation with netlist generated by kicad. Can you set up a document dir ?

and, how could I help in improving this project ?

**Comment by ignamv** [comment]
Hi, glad you like it. 

Not sure what you mean by a document dir, like a documentation folder? Feel free to add that in a pull request. 

If you want to improve the project, any bug reports or fixes are great. Also, think of what you'd like ngspyce to do better or differently, and ask for it or even implement it.

**Comment by liubenyuan** [comment]
OK, I am now fixing some python-3 compilance issues. See if I could make some contribution to this project !
