### ISSUE TITLE
unable to find libngspice

### ISSUE THREAD

**Issue by schneidersoft** [ignamv/ngspyce#13]
On debian ngspyce is unable to find the ngspice library.

I had to make some slight modifications to the ngspice source to get it to compile (warnings treated as errors)
But after the usual ./configure --with-shared && make && sudo makeinstall dance the ngspice library lives in

/usr/local/lib/ngspice.so.0

However since find_library('ngspice') returns ngspice.so.0
CDLL(find_library('ngspice')) fails with:

OSError: libngspice.so.0: cannot open shared object file: No such file or directory

CDLL('/usr/local/lib/'+find_library('ngspice')) on the other hand finds the lib but fails for another reason:
OSError: /usr/local/lib/libngspice.so.0: undefined symbol: wantevtdata

**Comment by ignamv** [comment]
Maybe try adding /usr/local/lib to the `LD_LIBRARY_PATH` environment variable, or to `/etc/ld.so.conf`

Also, make sure you haven't built the shared library on a dirty source tree previously used to build the executable.

**Comment by schneidersoft** [comment]
LD_LIBRARY_PATH does the trick. I just found the similar closed issue.

Should we perhaps mention this in the README.md? seems like it would be pretty common to need to do this.

To me it seems kinda silly that find_library finds a lib that CDLL then does not. Is there a way we can make it work out of the box without the LD_LIBRARY_PATH modification?

**Comment by endolith** [comment]
Yes, in README
